### ISSUE TITLE
Need support for zshrc history without EXTENDED_HISTORY option being enabled in ~/.zshrc

### ISSUE THREAD

**Issue by Ilhan-Personal** [quentinlintz/cmdtop#4]
My system by default did not have EXTENDED_HISTORY flag enabled in ~/.zshrc
so when I did a `go run .` I kept getting an empty reply in my terminal and the reason for that turned out to be that the code only supported the EXTENDED_HISTORY format.

I think I also know how to make a fix for this, Can you please assign this to me @quentinlintz ?

**Comment by quentinlintz** [comment]
I don't have that flag set either. What format is extended history in?

My zsh history is stored as:
```
: 1720920368:0;yay -Syu
: 1720920418:0;btop
: 1720990639:0;curl wttr.in
: 1720991026:0;cat ~/.zshrc
: 1720991044:0;history 10
: 1720991094:0;echo $EXTENDED_HISTORY
```

**Comment by Ilhan-Personal** [comment]
My apologies its not a flag, its an option in the zsh shell
Initially my zsh format was like this 
```
git clone git@github.com:quentinlintz/cmdtop.git
cd cmdtop
code .
cat ~/.zsh_history
websocat ws://localhost:8080/ws
websocat ws://localhost:8080/ws
```

but after running setopt EXTENDED_HISTORY in the ~/.zshrc file my format changed to this
```
: 1720982699:0;cat /Users/ilhan/.zsh_history
: 1720982707:25;less /Users/ilhan/.zsh_history
: 1721022246:0;cat /Users/ilhan/.zsh_history
: 1721022303:4;less /Users/ilhan/.zsh_history
: 1721022309:0;cat /Users/ilhan/.zsh_history
```
