### ISSUE TITLE
add support for fish parser

### ISSUE THREAD

**Issue by Ilhan-Personal** [quentinlintz/cmdtop#6]
this seems to be the next logical step in the roadmap
@quentinlintz could I please take this up XD?

**Comment by quentinlintz** [comment]
Yes for sure, thanks again!! Also looking for interesting and cool ways to display the top commands too, so let me know if you happen to have any ideas there. I might cut v0.2.0 today or tomorrow and then the fish parser could be part of v0.3.0 👍🏻

**Comment by Ilhan-Personal** [comment]
Thanks @quentinlintz !
yeah sure I'll let you know if something comes to mind :) 
Do we have a discord/slack channel for this project? feel like it would be easier to discuss stuff there, what do you think?

**Comment by quentinlintz** [comment]
I think that could be a good idea, any other feature ideas that come to mind that would take substantial effort? I was planning on making another Reddit post about cmdtop, if it gets more attention I'll create a Discord or Slack for better communication 😄

**Comment by Ilhan-Personal** [comment]
Thanks maybe we make a post on reddit and get some feedback to work on this XD

**Comment by quentinlintz** [comment]
Thanks again, this can be closed. I should install the fish shell and test it out to investigate if the output is as accurate as the zsh and bash parsers. I honestly don't know much about how fish works 😅

**Comment by Ilhan-Personal** [comment]
True true, I'll get some time this week to test it more as well....once we're thorough about it all we can make a release :)
